'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Mail, MessageCircle, PlayCircle, Search, Star, X } from 'lucide-react';
import { destinations, destinationImages, galleryImages, Locale, localizedPath, testimonials, tours, transportServices, values, whyChoose } from '@/lib/site-data';

export function SectionHeading({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) {
  return <div className="mx-auto mb-12 max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.32em] text-gold">{eyebrow}</p><h1 className="mt-3 font-display text-4xl font-semibold text-midnight dark:text-white sm:text-5xl">{title}</h1>{subtitle && <p className="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">{subtitle}</p>}<div className="gold-divider" /></div>;
}

export function PrimaryButton({ href, children }: { href: string; children: React.ReactNode }) {
  return <Link href={href} className="focus-ring inline-flex items-center justify-center gap-2 rounded-full bg-gold px-6 py-3 font-bold text-midnight shadow-glow transition hover:-translate-y-1 hover:bg-amber-300">{children}<ArrowRight size={18}/></Link>;
}

export function OutlineButton({ href, children }: { href: string; children: React.ReactNode }) {
  return <Link href={href} className="focus-ring inline-flex items-center justify-center gap-2 rounded-full border border-white/40 bg-white/10 px-6 py-3 font-bold text-white backdrop-blur transition hover:-translate-y-1 hover:bg-white/20">{children}</Link>;
}

export function Hero({ locale, t }: { locale: Locale; t: any }) {
  return <section className="relative flex min-h-screen items-center overflow-hidden bg-midnight pt-20 text-white"><div className="absolute inset-0"><Image src="https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=2200&q=85" alt="Luxury tropical Madagascar beach" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-midnight via-midnight/65 to-lagoon-700/30"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(214,167,86,.28),transparent_32%)]"/></div><div className="luxury-container relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="animate-fadeUp"><p className="mb-5 inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-bold uppercase tracking-[0.25em] text-lagoon-100 backdrop-blur">{t.home.eyebrow}</p><h1 className="font-display text-5xl font-semibold leading-tight sm:text-6xl lg:text-7xl">{t.home.title}</h1><p className="mt-6 max-w-2xl text-xl leading-9 text-white/85">{t.home.subtitle}</p><p className="mt-4 max-w-2xl text-white/70">{t.home.intro}</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><PrimaryButton href={localizedPath(locale, '/contact')}>{t.common.quote}</PrimaryButton><OutlineButton href="https://wa.me/261340000000"><MessageCircle size={18}/>{t.common.whatsapp}</OutlineButton></div></div><div className="glass-panel animate-float rounded-[2rem] p-6"><div className="grid grid-cols-3 gap-4 text-center"><Counter value="10+" label="Years"/><Counter value="900+" label="Guests"/><Counter value="24/7" label="Care"/></div><div className="mt-6 rounded-[1.5rem] bg-white/10 p-5"><p className="font-display text-2xl text-gold">Private island concierge</p><p className="mt-2 text-sm text-white/75">Custom boats, guides, vehicles, boutique stays and warm local hospitality.</p></div></div></div></section>;
}

function Counter({ value, label }: { value: string; label: string }) { return <div className="rounded-3xl bg-white/10 p-4"><div className="font-display text-3xl text-gold">{value}</div><div className="text-xs uppercase tracking-[0.2em] text-white/65">{label}</div></div>; }

export function WhyChoose({ title }: { title: string }) { return <section className="section-padding bg-white dark:bg-slate-950"><div className="luxury-container"><SectionHeading title={title} subtitle="Boutique service, local intelligence and premium logistics for a smoother Madagascar journey." /> <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{whyChoose.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-[2rem] border border-slate-100 bg-white p-6 shadow-luxury transition hover:-translate-y-2 dark:border-white/10 dark:bg-white/5"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-lagoon-50 text-lagoon-700 dark:bg-lagoon-500/20 dark:text-lagoon-100"><Icon/></div><h3 className="mt-6 font-display text-2xl text-midnight dark:text-white">{title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{text}</p></div>)}</div></div></section>; }

export function DestinationsGrid({ title, subtitle, searchLabel }: { title: string; subtitle: string; searchLabel?: string }) {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => destinations.filter((d) => `${d.name} ${d.tag} ${d.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <section className="section-padding bg-slate-50 dark:bg-slate-900"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/>{searchLabel && <label className="mx-auto mb-10 flex max-w-xl items-center gap-3 rounded-full border border-slate-200 bg-white px-5 py-3 shadow-sm dark:border-white/10 dark:bg-white/5"><Search className="text-gold"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={searchLabel} className="w-full bg-transparent outline-none"/></label>}<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{filtered.map((item) => <article key={item.name} className="group overflow-hidden rounded-[2rem] bg-white shadow-luxury dark:bg-white/5"><div className="relative h-64"><Image src={destinationImages[item.key]} alt={item.name} fill className="object-cover transition duration-700 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-midnight/80 to-transparent"/><span className="absolute left-4 top-4 rounded-full bg-gold px-3 py-1 text-xs font-bold text-midnight">{item.tag}</span><h3 className="absolute bottom-4 left-4 font-display text-3xl text-white">{item.name}</h3></div><p className="p-5 text-slate-600 dark:text-slate-300">{item.description}</p></article>)}</div></div></section>;
}

export function ToursGrid({ locale = 'en', title, subtitle, book, price }: { locale?: Locale; title: string; subtitle: string; book: string; price: string }) { return <section className="section-padding bg-white dark:bg-slate-950"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{tours.map((tour) => <article key={tour.title} className="overflow-hidden rounded-[2rem] border border-slate-100 bg-white shadow-luxury dark:border-white/10 dark:bg-white/5"><div className="relative h-64"><Image src={tour.image} alt={tour.title} fill className="object-cover"/><div className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-sm font-bold text-midnight"><CalendarDays className="mr-1 inline" size={16}/>{tour.duration}</div></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="font-display text-2xl text-midnight dark:text-white">{tour.title}</h3><span className="rounded-full bg-lagoon-50 px-3 py-1 text-xs font-bold text-lagoon-700 dark:bg-lagoon-500/20 dark:text-lagoon-100">{price}</span></div><p className="mt-3 text-slate-600 dark:text-slate-300">{tour.description}</p><Link href={localizedPath(locale, '/contact')} className="mt-6 inline-flex rounded-full bg-midnight px-5 py-2.5 font-bold text-white hover:bg-lagoon-700 dark:bg-gold dark:text-midnight">{book}</Link></div></article>)}</div></div></section>; }

export function ValuesSection({ title }: { title: string }) { return <section className="section-padding bg-slate-50 dark:bg-slate-900"><div className="luxury-container"><SectionHeading title={title}/><div className="grid gap-6 md:grid-cols-4">{values.map((value, index) => <div key={value.title} className="rounded-[2rem] bg-white p-6 shadow-luxury dark:bg-white/5"><span className="font-display text-5xl text-gold">0{index+1}</span><h3 className="mt-5 font-display text-2xl">{value.title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{value.text}</p></div>)}</div></div></section>; }

export function TransportServices({ title, subtitle }: { title: string; subtitle: string }) { return <section className="section-padding bg-white dark:bg-slate-950"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{transportServices.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-[2rem] border border-slate-100 p-6 shadow-luxury dark:border-white/10"><Icon className="text-gold" size={38}/><h2 className="mt-6 font-display text-2xl">{title}</h2><p className="mt-3 text-slate-600 dark:text-slate-300">{text}</p></div>)}</div></div></section>; }

export function GallerySection({ title, subtitle, videos }: { title: string; subtitle: string; videos?: string }) {
  const [active, setActive] = useState<string | null>(null);
  return <section className="section-padding bg-slate-50 dark:bg-slate-900"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/><div className="masonry">{galleryImages.map((src, i) => <button key={src} onClick={() => setActive(src)} className="masonry-item focus-ring group relative h-80 w-full overflow-hidden rounded-[2rem] shadow-luxury"><Image src={src} alt={`Madagascar gallery ${i+1}`} fill className="object-cover transition duration-700 group-hover:scale-110"/></button>)}</div>{videos && <div className="mt-14 rounded-[2rem] bg-luxury-gradient p-8 text-white shadow-luxury"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-display text-3xl">{videos}</h2><p className="mt-2 text-white/75">Drone-style island previews, reef moments and destination teasers for your quote consultation.</p></div><button className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 font-bold text-midnight"><PlayCircle/> Watch sample reel</button></div></div>}{active && <div className="fixed inset-0 z-[80] grid place-items-center bg-midnight/90 p-4" onClick={() => setActive(null)}><button className="absolute right-6 top-6 rounded-full bg-white p-3 text-midnight" aria-label="Close lightbox"><X/></button><div className="relative h-[80vh] w-full max-w-5xl"><Image src={active} alt="Expanded Madagascar gallery" fill className="object-contain"/></div></div>}</div></section>;
}

export function TestimonialsSection({ title, subtitle }: { title: string; subtitle: string }) { return <section className="section-padding bg-white dark:bg-slate-950"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/><div className="grid gap-6 md:grid-cols-3">{testimonials.map((item) => <article key={item.name} className="rounded-[2rem] border border-slate-100 bg-white p-6 shadow-luxury dark:border-white/10 dark:bg-white/5"><div className="flex gap-1 text-gold">{Array.from({length:item.rating}).map((_,i)=><Star key={i} fill="currentColor" size={18}/>)}</div><p className="mt-5 text-lg leading-8 text-slate-700 dark:text-slate-200">“{item.text}”</p><div className="mt-6 flex items-center gap-4"><Image src={item.photo} alt={item.name} width={56} height={56} className="h-14 w-14 rounded-full object-cover"/><div><h3 className="font-bold">{item.name}</h3><p className="text-sm text-slate-500">{item.country}</p></div></div></article>)}</div></div></section>; }

export function ContactForms({ title, subtitle, formTitle, newsletter }: { title: string; subtitle: string; formTitle: string; newsletter: string }) { return <section className="section-padding bg-slate-50 dark:bg-slate-900"><div className="luxury-container"><SectionHeading title={title} subtitle={subtitle}/><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><form className="rounded-[2rem] bg-white p-6 shadow-luxury dark:bg-white/5"><h2 className="font-display text-3xl">{formTitle}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Name"/><input className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Email"/><input className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Travel dates"/><input className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Guests"/><select className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10"><option>Tailor-made tour</option><option>Airport transfer</option><option>VIP transport</option></select><input className="rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Budget range"/><textarea className="min-h-36 rounded-2xl border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10 sm:col-span-2" placeholder="Tell us about your dream Madagascar experience"/></div><button className="mt-6 rounded-full bg-gold px-6 py-3 font-bold text-midnight">Send request</button></form><aside className="grid gap-6"><div className="rounded-[2rem] bg-luxury-gradient p-7 text-white shadow-luxury"><MessageCircle className="text-gold"/><h2 className="mt-5 font-display text-3xl">WhatsApp concierge</h2><p className="mt-3 text-white/75">Fast answers for transfers, island excursions and urgent travel support.</p><a href="https://wa.me/261340000000" className="mt-6 inline-flex rounded-full bg-white px-5 py-3 font-bold text-midnight">Open WhatsApp</a></div><form className="rounded-[2rem] bg-white p-7 shadow-luxury dark:bg-white/5"><Mail className="text-gold"/><h2 className="mt-4 font-display text-2xl">{newsletter}</h2><div className="mt-4 flex gap-2"><input className="min-w-0 flex-1 rounded-full border border-slate-200 bg-transparent px-4 py-3 dark:border-white/10" placeholder="Email address"/><button className="rounded-full bg-midnight px-5 text-white dark:bg-gold dark:text-midnight">Join</button></div></form></aside></div><div className="mt-10 overflow-hidden rounded-[2rem] shadow-luxury"><iframe title="Google Maps Madagascar" src="https://www.google.com/maps?q=Nosy%20Be%20Madagascar&output=embed" className="h-96 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section>; }
